version: "3.7"

services:
  repl:
    build:
      context: .
      dockerfile: repl.Dockerfile
    image: polyneme/ads-query-eval-nb
    volumes:
      - ./repl:/home/jovyan/work
      - ./repl/configure_environment.sh:/usr/local/bin/before-notebook.d/configure_environment.sh
      - ./ads_query_eval:/code/ads_query_eval
    environment:
      ADS_API_TOKEN: "${ADS_API_TOKEN}"
    ports:
      - "8998:8888"

  app:
    ports:
      - "8000:8000"
    command: ["uvicorn", "ads_query_eval.app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./ads_query_eval:/code/ads_query_eval

  mongo:
    ports:
      - "57018:27017"

  dagster-dagit:
    ports:
      - "3000:3000"