version: "3.7"

services:
  app:
    build: .
    image: polyneme/ads-query-eval
    command: ["./wait-for-it.sh" , "terminus:6363" , "--strict" , "--timeout=300" , "--" , "uvicorn", "ads_query_eval.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - ./config.env
    expose:
      - "8000"
    restart: unless-stopped
    depends_on:
      - terminus

  terminus:
    image: terminusdb/terminusdb-server:v10.1.2
    tty: true
    volumes:
      - terminus_data:/app/terminusdb/storage
    restart: always
    env_file:
      - ./config.env
    environment:
      TERMINUSDB_SERVER_PORT: 6363
      TERMINUSDB_AUTOLOGIN_ENABLED: "true"
      TERMINUSDB_HTTPS_ENABLED: "false"

  dagster-postgresql:
    image: postgres:11
    volumes:
      - dagster_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"

  dagster-dagit:
    build: .
    image: polyneme/ads-query-eval
    working_dir: "/opt/dagster/home/"
    entrypoint: ["tini", "--", "./entrypoint-dagit.sh"]
    expose:
      - "3000"
    env_file:
      - ./config.env
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    depends_on:
      - dagster-postgresql

  dagster-daemon:
    build: .
    image: polyneme/ads-query-eval
    working_dir: "/opt/dagster/home/"
    entrypoint: ["tini", "--", "./entrypoint-daemon.sh"]
    restart: on-failure
    env_file:
      - ./config.env
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    depends_on:
      - dagster-postgresql

  snappass:
      image: polyneme/snappass
      stop_signal: SIGINT
      environment:
        REDIS_HOST: "snappass-redis"
        SECRET_KEY: ${SECRET_KEY}
      depends_on:
        - snappass-redis

  snappass-redis:
      image: "redis:latest"

volumes:
  terminus_data:
    name: ${COMPOSE_PROJECT_NAME}_terminus_data
    external: true
  dagster_postgres_data:
    name: ${COMPOSE_PROJECT_NAME}_dagster_postgres_data
    external: true
