version: "3.7"

services:
  repl:
    build:
      context: .
      dockerfile: repl.Dockerfile
    image: polyneme/ads-query-eval-nb
    volumes:
      - ./repl:/home/jovyan/work
      - ./repl/configure_environment.sh:/usr/local/bin/before-notebook.d/configure_environment.sh
      - ./ads_query_eval:/code/ads_query_eval
    env_file:
      - ./config.env
    ports:
      - "8998:8888"

  app:
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh" , "terminus:6363" , "--strict" , "--timeout=300" , "--", "uvicorn", "ads_query_eval.app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      SITE_URL: "http://localhost:8000"
    volumes:
      - ./ads_query_eval:/code/ads_query_eval

  terminus:
    ports:
      - "6364:6363"
    environment:
      TERMINUSDB_LOG_LEVEL: DEBUG

  dagster-dagit:
    ports:
      - "3000:3000"

  snappass:
    environment:
      NO_SSL: "True"
      HOST_OVERRIDE: "localhost:5000"
    ports:
      - "5000:5000"